/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: c10d9f5599dd3b6f741aee1b4e36f125)
interface __BaseEnv_Env {
	APPLE_BUNDLE_ID: "com.asakenas.shopwareapp";
	APPLE_ENVIRONMENT: "Production";
	SUBSCRIPTION_PRODUCT_ID: "com.asakenas.shopwareapp.ai.monthly";
	ANTHROPIC_MODEL: "claude-opus-4-8";
	AI_FEATURE_ENABLED: "true";
	MAX_REQUESTS_PER_MINUTE: "20";
	MAX_REQUESTS_PER_DAY: "500";
	MAX_TOKENS_PER_MONTH: "2000000";
	SKIP_ENTITLEMENT_CHECK: "false";
	USAGE_LIMITER: DurableObjectNamespace<import("./src/index").UsageLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UsageLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APPLE_BUNDLE_ID" | "APPLE_ENVIRONMENT" | "SUBSCRIPTION_PRODUCT_ID" | "ANTHROPIC_MODEL" | "AI_FEATURE_ENABLED" | "MAX_REQUESTS_PER_MINUTE" | "MAX_REQUESTS_PER_DAY" | "MAX_TOKENS_PER_MONTH" | "SKIP_ENTITLEMENT_CHECK">> {}
}
