/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false` (hash: ac7987c78f1d99cb3be25e55f29b7e70)
interface __BaseEnv_Env {
	APPLE_BUNDLE_ID: "com.asakenas.shopwareapp";
	APPLE_TEAM_ID: "ZHVUYJ68S9";
	APPLE_ENVIRONMENT: "Production";
	APP_ATTEST_REQUIRED: "true";
	APP_ATTEST_ALLOW_DEVELOPMENT: "false";
	SUBSCRIPTION_PRODUCT_ID: "com.asakenas.shopwareapp.ai.monthly";
	ANTHROPIC_MODEL: "claude-sonnet-5";
	AI_FEATURE_ENABLED: "true";
	MAX_REQUESTS_PER_MINUTE: "20";
	MAX_REQUESTS_PER_DAY: "500";
	MAX_TOKENS_PER_MONTH: "2000000";
	MAX_TOKENS_PER_REQUEST_RESERVATION: "250000";
	SKIP_ENTITLEMENT_CHECK: "false";
	USAGE_LIMITER: DurableObjectNamespace<import("./src/index").UsageLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UsageLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APPLE_BUNDLE_ID" | "APPLE_TEAM_ID" | "APPLE_ENVIRONMENT" | "APP_ATTEST_REQUIRED" | "APP_ATTEST_ALLOW_DEVELOPMENT" | "SUBSCRIPTION_PRODUCT_ID" | "ANTHROPIC_MODEL" | "AI_FEATURE_ENABLED" | "MAX_REQUESTS_PER_MINUTE" | "MAX_REQUESTS_PER_DAY" | "MAX_TOKENS_PER_MONTH" | "MAX_TOKENS_PER_REQUEST_RESERVATION" | "SKIP_ENTITLEMENT_CHECK">> {}
}
